name: mizu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  provider: ^6.0.5
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.4
  google_fonts: ^5.1.0
  swipe_to: ^1.0.2
  swipe_widget: ^0.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  
  uses-material-design: true
  assets: 
  - assets/
  # - assets\mizu_app_icon.png
    
