// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTXLEJ2W8SBqQpmxjadwQGwnIzH-kJpYc',
    appId: '1:862247011568:web:9144c50d9911ce93622e35',
    messagingSenderId: '862247011568',
    projectId: 'mizu-4b970',
    authDomain: 'mizu-4b970.firebaseapp.com',
    storageBucket: 'mizu-4b970.appspot.com',
    measurementId: 'G-55P8PVHBNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQ6PRW7kULqCBwOCInV3zHynR_KBwDsw',
    appId: '1:862247011568:android:0f9084c3ad788f8c622e35',
    messagingSenderId: '862247011568',
    projectId: 'mizu-4b970',
    storageBucket: 'mizu-4b970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7EYlnmzuPgxtValgxCzl22AU13oDZBM',
    appId: '1:862247011568:ios:e4e619abd0bf208a622e35',
    messagingSenderId: '862247011568',
    projectId: 'mizu-4b970',
    storageBucket: 'mizu-4b970.appspot.com',
    iosClientId: '862247011568-jhiscr646bi1468mop0c3qaqhmvkqpo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mizu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ7EYlnmzuPgxtValgxCzl22AU13oDZBM',
    appId: '1:862247011568:ios:c38ef5c9da4d836b622e35',
    messagingSenderId: '862247011568',
    projectId: 'mizu-4b970',
    storageBucket: 'mizu-4b970.appspot.com',
    iosClientId: '862247011568-8filu9ac79d8qidp9kgsrb7drhll8n98.apps.googleusercontent.com',
    iosBundleId: 'com.example.mizu.RunnerTests',
  );
}
